version: '3.8'
services:
  mongo:
    image: "mongo:6.0"
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://admin:password@mongo:27017
      SECRET_KEY: your_super_secret_key_change_this_in_production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      DEBUG: "True"
      HOST: 0.0.0.0
      PORT: 8000
      ALLOWED_ORIGINS: http://localhost,http://127.0.0.1
      ADMIN_EMAIL: admin@jobboard.com
      ADMIN_PASSWORD: admin123

volumes:
  mongo_data:
